
// This file has been generated by the GUI designer. Do not modify.
namespace EV3CommandAndControl
{
	public partial class CommandTemplateView
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget EV3CommandAndControl.CommandTemplateView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "EV3CommandAndControl.CommandTemplateView";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
