
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action ViewAction;

	private global::Gtk.Action ConnectionStatusAction;

	private global::Gtk.Action ViewAction1;

	private global::Gtk.Action ConnectionStatusAction1;

	private global::Gtk.Action FileAction1;

	private global::Gtk.Action ViewAction2;

	private global::Gtk.Action ConnectionStatusAction2;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Button button1;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Button button3;

	private global::Gtk.VBox vbox4;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label label4;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.ViewAction = new global::Gtk.Action("ViewAction", global::Mono.Unix.Catalog.GetString("View"), null, null);
		this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString("View");
		w1.Add(this.ViewAction, null);
		this.ConnectionStatusAction = new global::Gtk.Action("ConnectionStatusAction", global::Mono.Unix.Catalog.GetString("Connection Status"), null, null);
		this.ConnectionStatusAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Connection Status");
		w1.Add(this.ConnectionStatusAction, null);
		this.ViewAction1 = new global::Gtk.Action("ViewAction1", global::Mono.Unix.Catalog.GetString("View"), null, null);
		this.ViewAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("View");
		w1.Add(this.ViewAction1, null);
		this.ConnectionStatusAction1 = new global::Gtk.Action("ConnectionStatusAction1", global::Mono.Unix.Catalog.GetString("Connection Status"), null, null);
		this.ConnectionStatusAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Connection Status");
		w1.Add(this.ConnectionStatusAction1, null);
		this.FileAction1 = new global::Gtk.Action("FileAction1", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction1, null);
		this.ViewAction2 = new global::Gtk.Action("ViewAction2", global::Mono.Unix.Catalog.GetString("View"), null, null);
		this.ViewAction2.ShortLabel = global::Mono.Unix.Catalog.GetString("View");
		w1.Add(this.ViewAction2, null);
		this.ConnectionStatusAction2 = new global::Gtk.Action("ConnectionStatusAction2", global::Mono.Unix.Catalog.GetString("Connection Status"), null, null);
		this.ConnectionStatusAction2.ShortLabel = global::Mono.Unix.Catalog.GetString("Connection Status");
		w1.Add(this.ConnectionStatusAction2, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='FileAction1' action='FileAction1'/><menu name='ViewAction2' action='ViewAction2'/><menu name='ConnectionStatusAction2' action='ConnectionStatusAction2'/></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.vbox2.Add(this.button1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.button1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.hbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.vbox3.Add(this.button3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button3]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.hbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w7.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.vbox4.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hseparator1]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
		this.hbox5.Add(this.label4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label4]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox4.Add(this.hbox5);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox5]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox1.Add(this.vbox4);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox4]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
